services:
  - type: web
    name: plp-platform
    runtime: node
    region: oregon
    plan: free
    rootDir: plp-platform
    buildCommand: npm install --legacy-peer-deps && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_VERSION
        value: 22.16.0
      - key: NODE_ENV
        value: production
      - key: NEXT_PUBLIC_PRIVY_APP_ID
        sync: false
      - key: MONGODB_URI
        sync: false
      - key: MONGODB_PROD_DATABASE
        sync: false
      - key: NEXT_PUBLIC_SOLANA_NETWORK
        sync: false
      - key: NEXT_PUBLIC_PLP_PROGRAM_ID_MAINNET
        sync: false
      - key: HELIUS_API_KEY
        sync: false
      - key: NEXT_PUBLIC_HELIUS_MAINNET_RPC
        sync: false
      - key: NEXT_PUBLIC_HELIUS_WS_MAINNET
        sync: false
      - key: REDIS_URL
        sync: false
      - key: NEXT_PUBLIC_APP_URL
        sync: false
      - key: NEXT_PUBLIC_API_URL
        sync: false
      - key: NEXT_PUBLIC_PINATA_JWT
        sync: false
      - key: NEXT_PUBLIC_PINATA_GATEWAY_URL
        sync: false
