[features]
seeds = false
skip-lint = false

[toolchain]
anchor_version = "0.30.1"

[programs.localnet]
errors = "3jGpj7HYo3jctBApnjwZGW54hJCpNHooFfu5533WvXr4"

[programs.devnet]
errors = "2CjwEvY3gkErkEmM5wnLpRv9fq3msHjnPDVPQmaWhF3G"

[programs.mainnet]
errors = "Cpbf34RPMu991hxhADqs7dW2AkhWTjeAJCEwWVSSgoEG"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
client = "yarn run ts-node client/*.ts"
